dist: xenial
language: ruby
rvm: 2.6.3
cache:
  bundler: true
before_script: bundle exec rake compile
script: bundle exec rake test
notifications:
  email:
    on_success: never
    on_failure: change
